services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./database/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
    ports:
      - 5432:5432
