services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - ./database/1_initialize.sql:/docker-entrypoint-initdb.d/1_initialize.sql
      - ./database/2_test-data.sql:/docker-entrypoint-initdb.d/2_test-data.sql
      - ./database/3_example-games-news-feed.sql:/docker-entrypoint-initdb.d/3_example-games-news-feed.sql
    ports:
      - 5432:5432
